repositories {
    mavenLocal()
    mavenCentral()
    maven { // Anvil Lib
        name = "Cjsah Maven"
        url = "https://server.cjsah.net:1002/maven/releases"
        content {
            includeGroup "dev.anvilcraft.lib"
            includeGroup "dev.dubhe"
        }
    }
    maven { // Curios API
        name = "Illusive Soulworks maven"
        url = "https://maven.theillusivec4.top/"
    }
}
